version: '3.6'
services:
  bibliotheca-db:
    image: postgres
    container_name: bibliotheca-docker-db
    environment:
      POSTGRES_PASSWORD: bibliotheca
      POSTGRES_USER: bibliotheca
      POSTGRES_DB: bibliotheca
    ports:
      - "5432:5432"
    networks:
      - api-db
    expose:
      - 5432

  bibliotheca-api:
    build:
      context: ./bibliotheca-api
    image: njakopcic/bibliotheca
    container_name: bibliotheca-api
    ports:
      - "8080:8080"
    depends_on:
      - bibliotheca-db
    networks:
      - ui-api
      - api-db
    expose:
      - 8080

  bibliotheca-ui:
    build: ./bibliotheca-ui
    image: njakopcic/bibliotheca-ui
    container_name: bibliotheca-ui
    ports:
      - "8081:8081"
    depends_on:
      - bibliotheca-api
    networks:
      - ui-api

networks:
  api-db:
    driver: bridge
  ui-api:
    driver: bridge