spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bibliotheca-db:5432/bibliotheca
    username: bibliotheca
    password: bibliotheca
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true